COPY_EXISTING_REGEXP GLOB ~^.*\.itm$~ ~override~
	PATCH_IF (SHORT_AT 0x1c == 7) THEN BEGIN
		PATCH_IF (((BYTE_AT 0x1e) & 0x80) == 0) && (((BYTE_AT 0x1f) & 0x08) == 0) THEN BEGIN
			WRITE_BYTE 0x1f (THIS & 0xef)
			WRITE_BYTE 0x21 (THIS & 0xbf)
		END
	END
	PATCH_IF (SHORT_AT 0x1c == 2) || (SHORT_AT 0x1c == 0x0c) THEN BEGIN
		PATCH_IF (((BYTE_AT 0x1e) & 0x80) == 0) && (((BYTE_AT 0x1f) & 0x08) == 0) THEN BEGIN
			WRITE_BYTE 0x1f (THIS & 0xef)
		END
	END
BUT_ONLY
